# Generated by Django 3.0.3 on 2020-07-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200412_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
