# Generated by Django 3.0.3 on 2020-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdjango', '0006_auto_20200414_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
